controller_manager:
  ros__parameters:
    update_rate: 125
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_a_teleop_controller:
      type: position_controllers/JointGroupPositionController
    arm_b_teleop_controller:
      type: position_controllers/JointGroupPositionController
